languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Balance"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo.png"
  description = "Rallenta, respira, ritrova te stesso."

[params.author]
  name = "Balance"
    logo = "img/blowfish_logo.png"
  headline = "Rallenta, respira, ritrova te stesso."
  bio = "Rallenta, respira, ritrova te stesso."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },]
